# yamllint
image: dleskecc/tester.py

variables:
  PYLINTRC: tests/linting/extras/pylintrc
  PYTHONPATH: ${PYTHONPATH}:.
  #
  # image names
  TEST_IMAGE: "${CI_REGISTRY_IMAGE}:test"
  DEV_IMAGE: "${CI_REGISTRY_IMAGE}:dev"
  PROD_IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  SHA_IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"

before_script:
  - git submodule sync
  - git submodule update --init
  - docker login -u burst-ci -p "$ldapctnr_pull_token" $CI_REGISTRY

stages:
  - pre-test
  - test
  - build
  - pre-deploy
  - deploy

.code:
  only:
    changes:
      - .gitlab-ci.yml
      - ccldap
      - "i18n/*"
      - "app/**/*"
      - requirements.txt
      - "tests/**/*"
      - deployment/Dockerfile

.integration:
  variables:
    POSTGRES_PASSWORD: supersecretpassword
    BEAM_PGSQL_URI: postgresql://postgres:supersecretpassword@postgres/postgres
    BEAM_LDAP_URI: ldap://ldap
    BEAM_LDAP_SKIP_TLS: 'yes'
  services:
    - name: git.computecanada.ca:4567/dleske/ldap-ctnr
      alias: ldap
    - name: postgres

todos:
  except:
    - main
  allow_failure: true
  tags:
    - unprivileged
  stage: pre-test
  script:
    - tests/linting/todos

todos_main:
  only:
    - main
  allow_failure: true
  tags:
    - unprivileged
  stage: pre-test
  script:
    - tests/linting/todos && true; todos=$?
    - anybadge --label=todos --value=$todos --value-format=" %d " --file=todos.svg --use-max 1=green 5=yellow 10=orange 20=red
    - test $todos -eq 0
  artifacts:
    # create artifact even when the job fails, which it should if todos > 0
    when: always
    paths: ['todos.svg']

syntax:
  extends: .code
  tags:
    - unprivileged
  stage: pre-test
  script:
    - tests/linting/test-all

unittest:
  extends: .code
  tags:
    - unprivileged
  stage: pre-test
  script:
    - apt-get install -y libldap2-dev libsasl2-dev
    - pip3 install -r requirements.txt
    - pybabel compile -d app/translations
    - pytest -v --cov=app tests/test_sqlite.py

integration:
  extends:
    - .code
    - .integration
  tags:
    - unprivileged
  stage: test
  script:
    - 'echo hi > /dev/tcp/postgres/5432 || echo "Could not contact Postgres container"'
    - 'echo hi > /dev/tcp/ldap/389 || echo "Could not contact LDAP container"'
    - apt-get install -y libldap2-dev libsasl2-dev
    - pip3 install -r requirements.txt
    - pybabel compile -d app/translations
    - pytest -v --cov=app tests/test_sqlite.py tests/test_pgsql.py tests/test_integration.py

build_test:
  extends: .code
  tags:
    - unprivileged
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull $TEST_IMAGE || true    # it's okay if this fails
    - buildinfo=$(git log -1 --date=format:%Y%m%d --format="%h\/%cd")
    - sed -i 's/Built with Flask/'$buildinfo'/' app/templates/base.html
    - docker build -f deployment/Dockerfile --cache-from $TEST_IMAGE -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

build_docker_development:
  extends: .code
  only:
    - main
  except:
    - tags
  tags:
    - unprivileged
  stage: pre-deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull $TEST_IMAGE || true    # it's okay if this fails
    - imagetag="${CI_REGISTRY_IMAGE}:dev"
    - buildinfo=$(git log -1 --date=format:%Y%m%d --format="%h\/%cd")
    - sed -i 's/Built with Flask/'$buildinfo'/' app/templates/base.html
    - docker build -f deployment/Dockerfile --cache-from $TEST_IMAGE -t $SHA_IMAGE -t $DEV_IMAGE .
    - docker push $SHA_IMAGE
    - docker push $DEV_IMAGE

build_docker_release:
  extends: .code
  only:
    - tags
  tags:
    - unprivileged
  stage: pre-deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull $TEST_IMAGE || true    # it's okay if this fails
    - sed -i 's/Built with Flask/'$CI_COMMIT_TAG'/' app/templates/base.html
    - docker build -f deployment/Dockerfile --cache-from $TEST_IMAGE -t $SHA_IMAGE -t $PROD_IMAGE .
    - docker push $SHA_IMAGE
    - docker push $PROD_IMAGE

deploy_development:
  extends: .code
  # failure allowed while Kubernetes down
  allow_failure: true
  only:
    - main
  except:
    - tags
  tags:
    - unprivileged
  stage: deploy
  script:
    - kubectl --kubeconfig="$K8S_CONFIG" patch deployment beam-dev -p '{"spec":{"template":{"spec":{"containers":[{"name":"beam","image":"'${SHA_IMAGE}'"}]}}}}'

deploy_release:
  extends: .code
  # failure allowed while Kubernetes down
  allow_failure: true
  only:
    - tags
  tags:
    - unprivileged
  stage: deploy
  script:
    - kubectl version
    - kubectl --kubeconfig="$K8S_CONFIG" patch deployment beam -p '{"spec":{"template":{"spec":{"containers":[{"name":"beam","image":"'${PROD_IMAGE}'"}]}}}}'
