#!/bin/sh
# Git apparently always sets the working directory to the root of the
# workspace, so using relative paths from there is fine.

export PYTHONPATH=.:$PYTHONPATH

# linting
tests/linting/test-all || exit 1

# test pgsql if container is running
pgsql_testing=""
ldap_testing=""
if docker ps | grep -q postgres-beam
then
  pgsql_testing="tests/test_pgsql.py"

  # test if LDAP container is running
  if docker ps | grep -q ldap-beam
  then
    ldap_testing="tests/test_integration.py"
  fi
fi

# functional testing
pytest -v --cov=app --cov-report=term --cov-report=html  tests/test_sqlite.py $pgsql_testing $ldap_testing || exit 1
